import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "el";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Navigation
    "nav.browse": "Browse Properties",
    "nav.list": "List Your Property",
    "nav.howItWorks": "How It Works",
    "nav.signIn": "Sign In",
    
    // Hero
    "hero.title": "Find Your Perfect Rental",
    "hero.subtitle": "Connect directly with property owners. No agents, no fees.",
    "hero.location": "Location",
    "hero.propertyType": "Property Type",
    "hero.priceRange": "Price Range",
    "hero.search": "Search Properties",
    "hero.apartment": "Apartment",
    "hero.house": "House",
    "hero.studio": "Studio",
    
    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.welcomeBack": "Welcome Back",
    "auth.loginDesc": "Enter your credentials to access your account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.loginButton": "Login",
    "auth.loggingIn": "Logging in...",
    "auth.createAccount": "Create Account",
    "auth.signupDesc": "Join HomiDirect and start your rental journey",
    "auth.fullName": "Full Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.iAmA": "I am a:",
    "auth.tenant": "Tenant (looking for rental properties)",
    "auth.propertyOwner": "Property Owner (want to list properties)",
    "auth.signUpButton": "Sign Up",
    "auth.creatingAccount": "Creating account...",
    "auth.loginSuccess": "Login successful",
    "auth.welcomeBackMsg": "Welcome back to HomiDirect!",
    "auth.accountCreated": "Account created",
    "auth.welcomeMsg": "Welcome to HomiDirect!",
    "auth.roleRequired": "Role required",
    "auth.roleRequiredMsg": "Please select at least one role (Tenant or Property Owner)",
    
    // List Property Info
    "listInfo.title": "List Your Property on HomiDirect",
    "listInfo.subtitle": "Connect with renters directly and save on agent fees. No commission, complete control.",
    "listInfo.noFees": "No Agent Fees",
    "listInfo.noFeesDesc": "Keep 100% of your rental income without paying commission",
    "listInfo.setPrice": "Set Your Price",
    "listInfo.setPriceDesc": "You control the pricing and terms of your rental property",
    "listInfo.directContact": "Direct Contact",
    "listInfo.directContactDesc": "Communicate directly with potential renters instantly",
    "listInfo.howToList": "How to List Your Property",
    "listInfo.howToListDesc": "Follow these simple steps to get your property listed",
    "listInfo.step1": "Register as a Property Owner",
    "listInfo.step1Desc": "Create an account and select \"Property Owner\" during registration",
    "listInfo.step2": "Fill Out Property Details",
    "listInfo.step2Desc": "Provide accurate information about your property including location, price, and amenities",
    "listInfo.step3": "Upload Photos & Verification",
    "listInfo.step3Desc": "Add high-quality photos and upload a verification document (utility bill or title deed)",
    "listInfo.step4": "Connect with Renters",
    "listInfo.step4Desc": "Once approved, your property goes live and tenants can contact you directly",
    "listInfo.needRegister": "You need to be registered as a Property Owner to list your property",
    "listInfo.tenantAccount": "Your account is registered as a Tenant. Please create a new account as a Property Owner to list properties.",
    "listInfo.registerButton": "Register as Property Owner",
    "listInfo.startListing": "Start Listing",
    
    // List Property Form
    "listForm.title": "List Your Property",
    "listForm.subtitle": "Fill in the details below to list your property and connect with renters directly.",
    "listForm.propertyDetails": "Property Details",
    "listForm.propertyDetailsDesc": "Provide accurate information to attract quality renters",
    "listForm.propertyTitle": "Property Title",
    "listForm.propertyType": "Property Type",
    "listForm.monthlyRent": "Monthly Rent ($)",
    "listForm.location": "Location",
    "listForm.bedrooms": "Bedrooms",
    "listForm.bathrooms": "Bathrooms",
    "listForm.area": "Area (sq ft)",
    "listForm.description": "Description",
    "listForm.amenities": "Amenities",
    "listForm.propertyImages": "Property Images",
    "listForm.clickUpload": "Click to upload property images",
    "listForm.uploadDesc": "Upload at least 3 photos (Max 10MB each)",
    "listForm.imagesSelected": "image(s) selected",
    "listForm.verification": "Property Verification Document",
    "listForm.verificationRequired": "Required",
    "listForm.verificationDesc": "Upload a document to verify property ownership (e.g., utility bill, property tax bill, or title deed)",
    "listForm.clickVerification": "Click to upload verification document",
    "listForm.verificationFileDesc": "PDF, JPG, PNG, or DOC (Max 10MB)",
    "listForm.contactInfo": "Contact Information",
    "listForm.yourName": "Your Name",
    "listForm.phone": "Phone Number",
    "listForm.availableFrom": "Available From",
    "listForm.submitButton": "List My Property",
    "listForm.listed": "Property Listed!",
    "listForm.listedDesc": "Your property has been submitted for review.",
    "listForm.accessDenied": "Access Denied",
    "listForm.accessDeniedDesc": "You must be registered as a Property Owner to list properties.",
    
    // Hero
    "hero.perfectHome": "Find Your Perfect Home",
    "hero.withoutHassle": "Without The Hassle",
    "hero.connectDirectly": "Connect directly with property owners. No agents, no extra fees. Just honest rentals.",
    "hero.searchPlaceholder": "Location, neighborhood, or city...",
    "hero.apartments": "Apartments",
    "hero.houses": "Houses",
    "hero.studios": "Studios",
    "hero.sharedSpaces": "Shared Spaces",
    "hero.activeListings": "Active Listings",
    "hero.propertyOwners": "Property Owners",
    "hero.agentFees": "Agent Fees",
    
    // Property Card
    "propertyCard.perMonth": "per month",
    "propertyCard.beds": "Beds",
    "propertyCard.baths": "Baths",
    "propertyCard.featured": "Featured",
    
    // Home Page
    "home.featuredProperties": "Featured Properties",
    "home.handPicked": "Hand-picked properties from trusted owners",
    "home.viewAll": "View All",
    "home.viewAllProperties": "View All Properties",
    "home.whyChoose": "Why Choose HomiDirect?",
    "home.whyChooseDesc": "We connect renters directly with property owners, eliminating unnecessary costs and complications",
    "home.noAgentFees": "No Agent Fees",
    "home.noAgentFeesDesc": "Save thousands by dealing directly with property owners. No middleman, no extra costs.",
    "home.verifiedListings": "Verified Listings",
    "home.verifiedListingsDesc": "Every property and owner is verified to ensure a safe and trustworthy rental experience.",
    "home.directCommunication": "Direct Communication",
    "home.directCommunicationDesc": "Chat directly with property owners, schedule viewings, and negotiate terms on your terms.",
    "home.readyToFind": "Ready to Find Your Perfect Home?",
    "home.joinThousands": "Join thousands of renters who have found their dream homes without paying agent fees",
    "home.startSearching": "Start Searching",
    "home.listYourProperty": "List Your Property",
    "home.allRightsReserved": "© 2024 HomiDirect. All rights reserved.",
    "home.privacyPolicy": "Privacy Policy",
    "home.termsOfService": "Terms of Service",
    "home.contactUs": "Contact Us",
    
    // How It Works
    "howItWorks.title": "How HomiDirect Works",
    "howItWorks.subtitle": "Connect directly with property owners or find your ideal tenants. No agents, no commissions, no hassle.",
    "howItWorks.forTenants": "For Tenants",
    "howItWorks.forTenantsDesc": "Find your dream rental property and connect directly with owners in four simple steps",
    "howItWorks.forOwners": "For Property Owners",
    "howItWorks.forOwnersDesc": "List your property and find quality tenants without paying agent commissions",
    "howItWorks.step": "Step",
    "howItWorks.tenant.step1.title": "Search Properties",
    "howItWorks.tenant.step1.desc": "Browse through our extensive listing of properties. Use filters to find exactly what you're looking for - location, price, size, and amenities.",
    "howItWorks.tenant.step2.title": "Review Details",
    "howItWorks.tenant.step2.desc": "Check property details, photos, and owner information. No hidden fees, no agent commissions - just transparent information.",
    "howItWorks.tenant.step3.title": "Contact Owner Directly",
    "howItWorks.tenant.step3.desc": "Message the property owner directly through our platform. Ask questions, schedule viewings, and negotiate terms without intermediaries.",
    "howItWorks.tenant.step4.title": "Finalize Agreement",
    "howItWorks.tenant.step4.desc": "Once you've found your perfect home, finalize the rental agreement directly with the owner. Save on agent fees and move in faster.",
    "howItWorks.owner.step1.title": "List Your Property",
    "howItWorks.owner.step1.desc": "Create a detailed listing with photos, description, and amenities. It's free and takes just a few minutes to get started.",
    "howItWorks.owner.step2.title": "Verify Your Identity",
    "howItWorks.owner.step2.desc": "Complete our simple verification process to build trust with potential tenants. Your profile helps renters feel confident.",
    "howItWorks.owner.step3.title": "Manage Inquiries",
    "howItWorks.owner.step3.desc": "Receive and respond to inquiries directly. Schedule viewings at your convenience and communicate with potential tenants.",
    "howItWorks.owner.step4.title": "Select Your Tenant",
    "howItWorks.owner.step4.desc": "Review interested tenants, conduct your own screening, and select the best fit. Finalize the agreement on your terms.",
    "howItWorks.startSearchingProperties": "Start Searching Properties",
    "howItWorks.whyChoose": "Why Choose HomiDirect?",
    "howItWorks.commissionFees": "Commission Fees",
    "howItWorks.directCommunication": "Direct Communication",
    "howItWorks.quickConnections": "Quick Connections",
    "howItWorks.goToHomepage": "Go to Homepage",
    "howItWorks.footer": "© 2024 HomiDirect. Connecting property owners and tenants directly.",
    
    // Search Results
    "search.placeholder": "Search by location, property type...",
    "search.filters": "Filters",
    "search.search": "Search",
    "search.propertyType": "Property Type",
    "search.allTypes": "All Types",
    "search.apartment": "Apartment",
    "search.house": "House",
    "search.studio": "Studio",
    "search.penthouse": "Penthouse",
    "search.townhouse": "Townhouse",
    "search.loft": "Loft",
    "search.bedrooms": "Bedrooms",
    "search.bathrooms": "Bathrooms",
    "search.any": "Any",
    "search.priceRange": "Price Range",
    "search.results": "Search Results",
    "search.foundProperties": "Found {count} properties in {location}",
    "search.sortBy": "Sort by",
    "search.featuredFirst": "Featured First",
    "search.priceLowToHigh": "Price: Low to High",
    "search.priceHighToLow": "Price: High to Low",
    "search.newestFirst": "Newest First",
    "search.previous": "Previous",
    "search.next": "Next",
    
    // Common
    "common.selectType": "Select type",
    "common.select": "Select",
    "common.footer": "© 2024 HomiDirect. Connect directly, rent confidently.",

    // Privacy Policy
    "privacy.title": "Privacy Policy",
    "privacy.lastUpdated": "Last updated: November 2024",
    "privacy.backToHome": "Back to Home",
    "privacy.section1.title": "1. Information We Collect",
    "privacy.section1.content": "We collect information you provide directly to us, including your name, email address, phone number, and property details when you create an account or list a property on HomiDirect.",
    "privacy.section2.title": "2. How We Use Your Information",
    "privacy.section2.content": "We use the information we collect to:",
    "privacy.section2.item1": "Provide, maintain, and improve our services",
    "privacy.section2.item2": "Process and complete transactions",
    "privacy.section2.item3": "Send you technical notices and support messages",
    "privacy.section2.item4": "Communicate with you about properties, services, and events",
    "privacy.section3.title": "3. Information Sharing",
    "privacy.section3.content": "We do not sell or rent your personal information to third parties. We may share your information only with your consent or as required by law.",
    "privacy.section4.title": "4. Data Security",
    "privacy.section4.content": "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    "privacy.section5.title": "5. Your Rights",
    "privacy.section5.content": "You have the right to access, update, or delete your personal information at any time. You can do this through your account settings or by contacting us.",
    "privacy.section6.title": "6. Contact Us",
    "privacy.section6.content": "If you have any questions about this Privacy Policy, please contact us at privacy@homidirect.com",

    // Terms of Service
    "terms.title": "Terms of Service",
    "terms.lastUpdated": "Last updated: November 2024",
    "terms.backToHome": "Back to Home",
    "terms.section1.title": "1. Acceptance of Terms",
    "terms.section1.content": "By accessing and using HomiDirect, you accept and agree to be bound by the terms and provision of this agreement.",
    "terms.section2.title": "2. Use License",
    "terms.section2.content": "Permission is granted to temporarily use HomiDirect for personal, non-commercial transitory viewing only.",
    "terms.section3.title": "3. User Responsibilities",
    "terms.section3.content": "As a user of HomiDirect, you agree to:",
    "terms.section3.item1": "Provide accurate and truthful information",
    "terms.section3.item2": "Maintain the security of your account credentials",
    "terms.section3.item3": "Not engage in fraudulent or illegal activities",
    "terms.section3.item4": "Respect other users and follow community guidelines",
    "terms.section4.title": "4. Property Listings",
    "terms.section4.content": "Property owners are responsible for the accuracy of their listings and must provide valid verification documents. HomiDirect reserves the right to remove any listing that violates our terms.",
    "terms.section5.title": "5. Disclaimer",
    "terms.section5.content": "HomiDirect acts as a platform to connect property owners and renters. We do not guarantee the accuracy of listings or the conduct of users. All rental agreements are made directly between parties.",
    "terms.section6.title": "6. Limitation of Liability",
    "terms.section6.content": "HomiDirect shall not be liable for any damages arising from the use of our service, including but not limited to direct, indirect, incidental, or consequential damages.",
    "terms.section7.title": "7. Changes to Terms",
    "terms.section7.content": "We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.",

    // Contact Page
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "contact.backToHome": "Back to Home",
    "contact.email": "Email",
    "contact.phone": "Phone",
    "contact.address": "Address",
    "contact.formTitle": "Send us a message",
    "contact.name": "Name",
    "contact.namePlaceholder": "Your full name",
    "contact.emailLabel": "Email",
    "contact.emailPlaceholder": "your.email@example.com",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "What is this regarding?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us how we can help you...",
    "contact.sendMessage": "Send Message",
    "contact.messageSent": "Message Sent!",
    "contact.messageSentDesc": "We've received your message and will get back to you soon.",
  },
  el: {
    // Navigation
    "nav.browse": "Αναζήτηση Ακινήτων",
    "nav.list": "Καταχωρήστε το Ακίνητό σας",
    "nav.howItWorks": "Πώς Λειτουργεί",
    "nav.signIn": "Σύνδεση",
    
    // Hero
    "hero.title": "Βρείτε την Ιδανική σας Ενοικίαση",
    "hero.subtitle": "Συνδεθείτε απευθείας με ιδιοκτήτες ακινήτων. Χωρίς μεσίτες, χωρίς προμήθειες.",
    "hero.location": "Τοποθεσία",
    "hero.propertyType": "Τύπος Ακινήτου",
    "hero.priceRange": "Εύρος Τιμής",
    "hero.search": "Αναζήτηση Ακινήτων",
    "hero.apartment": "Διαμέρισμα",
    "hero.house": "Μονοκατοικία",
    "hero.studio": "Στούντιο",
    
    // Auth
    "auth.login": "Σύνδεση",
    "auth.signup": "Εγγραφή",
    "auth.welcomeBack": "Καλώς Ήρθατε Πίσω",
    "auth.loginDesc": "Εισάγετε τα στοιχεία σας για πρόσβαση στον λογαριασμό σας",
    "auth.email": "Email",
    "auth.password": "Κωδικός",
    "auth.loginButton": "Σύνδεση",
    "auth.loggingIn": "Γίνεται σύνδεση...",
    "auth.createAccount": "Δημιουργία Λογαριασμού",
    "auth.signupDesc": "Εγγραφείτε στο HomiDirect και ξεκινήστε το ταξίδι ενοικίασης",
    "auth.fullName": "Ονοματεπώνυμο",
    "auth.confirmPassword": "Επιβεβαίωση Κωδικού",
    "auth.iAmA": "Είμαι:",
    "auth.tenant": "Ενοικιαστής (αναζητώ ακίνητα προς ενοικίαση)",
    "auth.propertyOwner": "Ιδιοκτήτης Ακινήτου (θέλω να καταχωρήσω ακίνητα)",
    "auth.signUpButton": "Εγγραφή",
    "auth.creatingAccount": "Δημιουργία λογαριασμού...",
    "auth.loginSuccess": "Επιτυχής σύνδεση",
    "auth.welcomeBackMsg": "Καλώς ήρθατε πίσω στο HomiDirect!",
    "auth.accountCreated": "Ο λογαριασμός δημιουργήθηκε",
    "auth.welcomeMsg": "Καλώς ήρθατε στο HomiDirect!",
    "auth.roleRequired": "Απαιτείται ρόλος",
    "auth.roleRequiredMsg": "Παρακαλώ επιλέξτε τουλάχιστον έναν ρόλο (Ενοικιαστής ή Ιδιοκτήτης Ακινήτου)",
    
    // List Property Info
    "listInfo.title": "Καταχωρήστε το Ακίνητό σας στο HomiDirect",
    "listInfo.subtitle": "Συνδεθείτε με ενοικιαστές απευθείας και εξοικονομήστε προμήθειες μεσιτών. Χωρίς προμήθεια, πλήρης έλεγχος.",
    "listInfo.noFees": "Χωρίς Προμήθειες Μεσίτη",
    "listInfo.noFeesDesc": "Κρατήστε το 100% του εισοδήματος από ενοίκια χωρίς προμήθεια",
    "listInfo.setPrice": "Ορίστε την Τιμή σας",
    "listInfo.setPriceDesc": "Εσείς ελέγχετε την τιμολόγηση και τους όρους του ακινήτου σας",
    "listInfo.directContact": "Άμεση Επικοινωνία",
    "listInfo.directContactDesc": "Επικοινωνήστε απευθείας με πιθανούς ενοικιαστές άμεσα",
    "listInfo.howToList": "Πώς να Καταχωρήσετε το Ακίνητό σας",
    "listInfo.howToListDesc": "Ακολουθήστε αυτά τα απλά βήματα για να καταχωρήσετε το ακίνητό σας",
    "listInfo.step1": "Εγγραφείτε ως Ιδιοκτήτης Ακινήτου",
    "listInfo.step1Desc": "Δημιουργήστε λογαριασμό και επιλέξτε \"Ιδιοκτήτης Ακινήτου\" κατά την εγγραφή",
    "listInfo.step2": "Συμπληρώστε τα Στοιχεία του Ακινήτου",
    "listInfo.step2Desc": "Παρέχετε ακριβείς πληροφορίες για το ακίνητό σας συμπεριλαμβανομένης της τοποθεσίας, τιμής και ανέσεων",
    "listInfo.step3": "Ανεβάστε Φωτογραφίες & Επαλήθευση",
    "listInfo.step3Desc": "Προσθέστε φωτογραφίες υψηλής ποιότητας και ανεβάστε ένα έγγραφο επαλήθευσης (λογαριασμός κοινής ωφέλειας ή τίτλος ιδιοκτησίας)",
    "listInfo.step4": "Συνδεθείτε με Ενοικιαστές",
    "listInfo.step4Desc": "Μόλις εγκριθεί, το ακίνητό σας θα είναι online και οι ενοικιαστές μπορούν να επικοινωνήσουν μαζί σας απευθείας",
    "listInfo.needRegister": "Πρέπει να είστε εγγεγραμμένος ως Ιδιοκτήτης Ακινήτου για να καταχωρήσετε ακίνητα",
    "listInfo.tenantAccount": "Ο λογαριασμός σας είναι εγγεγραμμένος ως Ενοικιαστής. Παρακαλώ δημιουργήστε νέο λογαριασμό ως Ιδιοκτήτης Ακινήτου για να καταχωρήσετε ακίνητα.",
    "listInfo.registerButton": "Εγγραφή ως Ιδιοκτήτης Ακινήτου",
    "listInfo.startListing": "Έναρξη Καταχώρησης",
    
    // List Property Form
    "listForm.title": "Καταχωρήστε το Ακίνητό σας",
    "listForm.subtitle": "Συμπληρώστε τα παρακάτω στοιχεία για να καταχωρήσετε το ακίνητό σας και να συνδεθείτε με ενοικιαστές απευθείας.",
    "listForm.propertyDetails": "Στοιχεία Ακινήτου",
    "listForm.propertyDetailsDesc": "Παρέχετε ακριβείς πληροφορίες για να προσελκύσετε ποιοτικούς ενοικιαστές",
    "listForm.propertyTitle": "Τίτλος Ακινήτου",
    "listForm.propertyType": "Τύπος Ακινήτου",
    "listForm.monthlyRent": "Μηνιαίο Ενοίκιο ($)",
    "listForm.location": "Τοποθεσία",
    "listForm.bedrooms": "Υπνοδωμάτια",
    "listForm.bathrooms": "Μπάνια",
    "listForm.area": "Εμβαδόν (τ.μ.)",
    "listForm.description": "Περιγραφή",
    "listForm.amenities": "Ανέσεις",
    "listForm.propertyImages": "Φωτογραφίες Ακινήτου",
    "listForm.clickUpload": "Κάντε κλικ για ανέβασμα φωτογραφιών ακινήτου",
    "listForm.uploadDesc": "Ανεβάστε τουλάχιστον 3 φωτογραφίες (Μέγιστο 10MB η καθεμία)",
    "listForm.imagesSelected": "φωτογραφία/-ίες επιλέχθηκαν",
    "listForm.verification": "Έγγραφο Επαλήθευσης Ακινήτου",
    "listForm.verificationRequired": "Απαιτείται",
    "listForm.verificationDesc": "Ανεβάστε ένα έγγραφο για επαλήθευση της ιδιοκτησίας (π.χ., λογαριασμός κοινής ωφέλειας, φορολογικό έγγραφο ή τίτλος ιδιοκτησίας)",
    "listForm.clickVerification": "Κάντε κλικ για ανέβασμα εγγράφου επαλήθευσης",
    "listForm.verificationFileDesc": "PDF, JPG, PNG ή DOC (Μέγιστο 10MB)",
    "listForm.contactInfo": "Στοιχεία Επικοινωνίας",
    "listForm.yourName": "Το Όνομά σας",
    "listForm.phone": "Τηλέφωνο",
    "listForm.availableFrom": "Διαθέσιμο Από",
    "listForm.submitButton": "Καταχώρηση Ακινήτου",
    "listForm.listed": "Το Ακίνητο Καταχωρήθηκε!",
    "listForm.listedDesc": "Το ακίνητό σας υποβλήθηκε προς έλεγχο.",
    "listForm.accessDenied": "Δεν Επιτρέπεται η Πρόσβαση",
    "listForm.accessDeniedDesc": "Πρέπει να είστε εγγεγραμμένος ως Ιδιοκτήτης Ακινήτου για να καταχωρήσετε ακίνητα.",
    
    // Hero
    "hero.perfectHome": "Βρείτε το Ιδανικό σας Σπίτι",
    "hero.withoutHassle": "Χωρίς Ταλαιπωρία",
    "hero.connectDirectly": "Συνδεθείτε απευθείας με ιδιοκτήτες ακινήτων. Χωρίς μεσίτες, χωρίς επιπλέον χρεώσεις. Απλώς ειλικρινείς ενοικιάσεις.",
    "hero.searchPlaceholder": "Τοποθεσία, γειτονιά ή πόλη...",
    "hero.apartments": "Διαμερίσματα",
    "hero.houses": "Μονοκατοικίες",
    "hero.studios": "Στούντιο",
    "hero.sharedSpaces": "Κοινόχρηστοι Χώροι",
    "hero.activeListings": "Ενεργές Καταχωρήσεις",
    "hero.propertyOwners": "Ιδιοκτήτες Ακινήτων",
    "hero.agentFees": "Προμήθειες Μεσίτη",
    
    // Property Card
    "propertyCard.perMonth": "το μήνα",
    "propertyCard.beds": "Κρεβάτια",
    "propertyCard.baths": "Μπάνια",
    "propertyCard.featured": "Προτεινόμενο",
    
    // Home Page
    "home.featuredProperties": "Προτεινόμενα Ακίνητα",
    "home.handPicked": "Επιλεγμένα ακίνητα από αξιόπιστους ιδιοκτήτες",
    "home.viewAll": "Προβολή Όλων",
    "home.viewAllProperties": "Προβολή Όλων των Ακινήτων",
    "home.whyChoose": "Γιατί να Επιλέξετε το HomiDirect;",
    "home.whyChooseDesc": "Συνδέουμε ενοικιαστές απευθείας με ιδιοκτήτες ακινήτων, εξαλείφοντας περιττά κόστη και επιπλοκές",
    "home.noAgentFees": "Χωρίς Προμήθειες Μεσίτη",
    "home.noAgentFeesDesc": "Εξοικονομήστε χιλιάδες συναλλασσόμενοι απευθείας με ιδιοκτήτες ακινήτων. Χωρίς μεσάζοντες, χωρίς επιπλέον κόστη.",
    "home.verifiedListings": "Επαληθευμένες Καταχωρήσεις",
    "home.verifiedListingsDesc": "Κάθε ακίνητο και ιδιοκτήτης επαληθεύεται για να διασφαλιστεί μια ασφαλής και αξιόπιστη εμπειρία ενοικίασης.",
    "home.directCommunication": "Άμεση Επικοινωνία",
    "home.directCommunicationDesc": "Συνομιλήστε απευθείας με ιδιοκτήτες ακινήτων, προγραμματίστε προβολές και διαπραγματευτείτε όρους με τους δικούς σας όρους.",
    "home.readyToFind": "Είστε Έτοιμοι να Βρείτε το Ιδανικό σας Σπίτι;",
    "home.joinThousands": "Ενταχθείτε σε χιλιάδες ενοικιαστές που βρήκαν τα σπίτια των ονείρων τους χωρίς να πληρώσουν προμήθειες μεσίτη",
    "home.startSearching": "Έναρξη Αναζήτησης",
    "home.listYourProperty": "Καταχωρήστε το Ακίνητό σας",
    "home.allRightsReserved": "© 2024 HomiDirect. Όλα τα δικαιώματα διατηρούνται.",
    "home.privacyPolicy": "Πολιτική Απορρήτου",
    "home.termsOfService": "Όροι Χρήσης",
    "home.contactUs": "Επικοινωνήστε Μαζί μας",
    
    // How It Works
    "howItWorks.title": "Πώς Λειτουργεί το HomiDirect",
    "howItWorks.subtitle": "Συνδεθείτε απευθείας με ιδιοκτήτες ακινήτων ή βρείτε τους ιδανικούς ενοικιαστές. Χωρίς μεσίτες, χωρίς προμήθειες, χωρίς ταλαιπωρία.",
    "howItWorks.forTenants": "Για Ενοικιαστές",
    "howItWorks.forTenantsDesc": "Βρείτε το ακίνητο ενοικίασης των ονείρων σας και συνδεθείτε απευθείας με ιδιοκτήτες σε τέσσερα απλά βήματα",
    "howItWorks.forOwners": "Για Ιδιοκτήτες Ακινήτων",
    "howItWorks.forOwnersDesc": "Καταχωρήστε το ακίνητό σας και βρείτε ποιοτικούς ενοικιαστές χωρίς να πληρώσετε προμήθειες μεσίτη",
    "howItWorks.step": "Βήμα",
    "howItWorks.tenant.step1.title": "Αναζήτηση Ακινήτων",
    "howItWorks.tenant.step1.desc": "Περιηγηθείτε στην εκτενή λίστα ακινήτων μας. Χρησιμοποιήστε φίλτρα για να βρείτε ακριβώς αυτό που ψάχνετε - τοποθεσία, τιμή, μέγεθος και ανέσεις.",
    "howItWorks.tenant.step2.title": "Έλεγχος Λεπτομερειών",
    "howItWorks.tenant.step2.desc": "Ελέγξτε τις λεπτομέρειες του ακινήτου, φωτογραφίες και πληροφορίες ιδιοκτήτη. Χωρίς κρυφές χρεώσεις, χωρίς προμήθειες μεσίτη - μόνο διαφανείς πληροφορίες.",
    "howItWorks.tenant.step3.title": "Επικοινωνία Απευθείας με τον Ιδιοκτήτη",
    "howItWorks.tenant.step3.desc": "Στείλτε μήνυμα στον ιδιοκτήτη του ακινήτου απευθείας μέσω της πλατφόρμας μας. Κάντε ερωτήσεις, προγραμματίστε προβολές και διαπραγματευτείτε όρους χωρίς μεσάζοντες.",
    "howItWorks.tenant.step4.title": "Οριστικοποίηση Συμφωνίας",
    "howItWorks.tenant.step4.desc": "Μόλις βρείτε το ιδανικό σας σπίτι, οριστικοποιήστε τη συμφωνία ενοικίασης απευθείας με τον ιδιοκτήτη. Εξοικονομήστε σε προμήθειες μεσίτη και μετακομίστε πιο γρήγορα.",
    "howItWorks.owner.step1.title": "Καταχωρήστε το Ακίνητό σας",
    "howItWorks.owner.step1.desc": "Δημιουργήστε μια λεπτομερή καταχώρηση με φωτογραφίες, περιγραφή και ανέσεις. Είναι δωρεάν και χρειάζονται μόνο λίγα λεπτά για να ξεκινήσετε.",
    "howItWorks.owner.step2.title": "Επαληθεύστε την Ταυτότητά σας",
    "howItWorks.owner.step2.desc": "Ολοκληρώστε τη διαδικασία επαλήθευσης για να χτίσετε εμπιστοσύνη με πιθανούς ενοικιαστές. Το προφίλ σας βοηθά τους ενοικιαστές να νιώθουν σίγουροι.",
    "howItWorks.owner.step3.title": "Διαχείριση Ερωτημάτων",
    "howItWorks.owner.step3.desc": "Λαμβάνετε και απαντάτε σε ερωτήματα απευθείας. Προγραμματίστε προβολές στη διευκόλυνσή σας και επικοινωνήστε με πιθανούς ενοικιαστές.",
    "howItWorks.owner.step4.title": "Επιλέξτε τον Ενοικιαστή σας",
    "howItWorks.owner.step4.desc": "Εξετάστε ενδιαφερόμενους ενοικιαστές, διεξάγετε τον δικό σας έλεγχο και επιλέξτε τον καλύτερο. Οριστικοποιήστε τη συμφωνία με τους δικούς σας όρους.",
    "howItWorks.startSearchingProperties": "Έναρξη Αναζήτησης Ακινήτων",
    "howItWorks.whyChoose": "Γιατί να Επιλέξετε το HomiDirect;",
    "howItWorks.commissionFees": "Προμήθειες",
    "howItWorks.directCommunication": "Άμεση Επικοινωνία",
    "howItWorks.quickConnections": "Γρήγορες Συνδέσεις",
    "howItWorks.goToHomepage": "Μετάβαση στην Αρχική",
    "howItWorks.footer": "© 2024 HomiDirect. Συνδέοντας ιδιοκτήτες ακινήτων και ενοικιαστές απευθείας.",
    
    // Search Results
    "search.placeholder": "Αναζήτηση κατά τοποθεσία, τύπο ακινήτου...",
    "search.filters": "Φίλτρα",
    "search.search": "Αναζήτηση",
    "search.propertyType": "Τύπος Ακινήτου",
    "search.allTypes": "Όλοι οι Τύποι",
    "search.apartment": "Διαμέρισμα",
    "search.house": "Μονοκατοικία",
    "search.studio": "Στούντιο",
    "search.penthouse": "Ρετιρέ",
    "search.townhouse": "Αρχοντικό",
    "search.loft": "Λοφτ",
    "search.bedrooms": "Υπνοδωμάτια",
    "search.bathrooms": "Μπάνια",
    "search.any": "Οποιοδήποτε",
    "search.priceRange": "Εύρος Τιμής",
    "search.results": "Αποτελέσματα Αναζήτησης",
    "search.foundProperties": "Βρέθηκαν {count} ακίνητα στο {location}",
    "search.sortBy": "Ταξινόμηση κατά",
    "search.featuredFirst": "Προτεινόμενα Πρώτα",
    "search.priceLowToHigh": "Τιμή: Από Χαμηλή σε Υψηλή",
    "search.priceHighToLow": "Τιμή: Από Υψηλή σε Χαμηλή",
    "search.newestFirst": "Νεότερα Πρώτα",
    "search.previous": "Προηγούμενο",
    "search.next": "Επόμενο",
    
    // Common
    "common.selectType": "Επιλογή τύπου",
    "common.select": "Επιλογή",
    "common.footer": "© 2024 HomiDirect. Συνδεθείτε απευθείας, ενοικιάστε με εμπιστοσύνη.",

    // Privacy Policy
    "privacy.title": "Πολιτική Απορρήτου",
    "privacy.lastUpdated": "Τελευταία ενημέρωση: Νοέμβριος 2024",
    "privacy.backToHome": "Επιστροφή στην Αρχική",
    "privacy.section1.title": "1. Πληροφορίες που Συλλέγουμε",
    "privacy.section1.content": "Συλλέγουμε πληροφορίες που μας παρέχετε απευθείας, συμπεριλαμβανομένου του ονόματος, email, τηλεφώνου και στοιχείων ακινήτου όταν δημιουργείτε λογαριασμό ή καταχωρείτε ακίνητο στο HomiDirect.",
    "privacy.section2.title": "2. Πώς Χρησιμοποιούμε τις Πληροφορίες σας",
    "privacy.section2.content": "Χρησιμοποιούμε τις πληροφορίες που συλλέγουμε για να:",
    "privacy.section2.item1": "Παρέχουμε, συντηρούμε και βελτιώνουμε τις υπηρεσίες μας",
    "privacy.section2.item2": "Επεξεργαζόμαστε και ολοκληρώνουμε συναλλαγές",
    "privacy.section2.item3": "Σας στέλνουμε τεχνικές ειδοποιήσεις και μηνύματα υποστήριξης",
    "privacy.section2.item4": "Επικοινωνούμε μαζί σας για ακίνητα, υπηρεσίες και εκδηλώσεις",
    "privacy.section3.title": "3. Κοινοποίηση Πληροφοριών",
    "privacy.section3.content": "Δεν πουλάμε ούτε ενοικιάζουμε τα προσωπικά σας δεδομένα σε τρίτους. Μπορούμε να κοινοποιήσουμε τις πληροφορίες σας μόνο με τη συγκατάθεσή σας ή όπως απαιτείται από το νόμο.",
    "privacy.section4.title": "4. Ασφάλεια Δεδομένων",
    "privacy.section4.content": "Εφαρμόζουμε κατάλληλα μέτρα ασφαλείας για την προστασία των προσωπικών σας δεδομένων από μη εξουσιοδοτημένη πρόσβαση, τροποποίηση, αποκάλυψη ή καταστροφή.",
    "privacy.section5.title": "5. Τα Δικαιώματά σας",
    "privacy.section5.content": "Έχετε το δικαίωμα να έχετε πρόσβαση, να ενημερώσετε ή να διαγράψετε τα προσωπικά σας δεδομένα ανά πάσα στιγμή. Μπορείτε να το κάνετε μέσω των ρυθμίσεων του λογαριασμού σας ή επικοινωνώντας μαζί μας.",
    "privacy.section6.title": "6. Επικοινωνήστε μαζί μας",
    "privacy.section6.content": "Εάν έχετε ερωτήσεις σχετικά με αυτήν την Πολιτική Απορρήτου, επικοινωνήστε μαζί μας στο privacy@homidirect.com",

    // Terms of Service
    "terms.title": "Όροι Χρήσης",
    "terms.lastUpdated": "Τελευταία ενημέρωση: Νοέμβριος 2024",
    "terms.backToHome": "Επιστροφή στην Αρχική",
    "terms.section1.title": "1. Αποδοχή Όρων",
    "terms.section1.content": "Με την πρόσβαση και χρήση του HomiDirect, αποδέχεστε και συμφωνείτε να δεσμεύεστε από τους όρους και τις διατάξεις αυτής της συμφωνίας.",
    "terms.section2.title": "2. Άδεια Χρήσης",
    "terms.section2.content": "Χορηγείται άδεια για προσωρινή χρήση του HomiDirect για προσωπική, μη εμπορική χρήση μόνο.",
    "terms.section3.title": "3. Ευθύνες Χρήστη",
    "terms.section3.content": "Ως χρήστης του HomiDirect, συμφωνείτε να:",
    "terms.section3.item1": "Παρέχετε ακριβείς και αληθείς πληροφορίες",
    "terms.section3.item2": "Διατηρείτε την ασφάλεια των στοιχείων του λογαριασμού σας",
    "terms.section3.item3": "Δεν συμμετέχετε σε δόλιες ή παράνομες δραστηριότητες",
    "terms.section3.item4": "Σέβεστε άλλους χρήστες και ακολουθείτε τις οδηγίες της κοινότητας",
    "terms.section4.title": "4. Καταχωρήσεις Ακινήτων",
    "terms.section4.content": "Οι ιδιοκτήτες ακινήτων είναι υπεύθυνοι για την ακρίβεια των καταχωρήσεών τους και πρέπει να παρέχουν έγκυρα έγγραφα επαλήθευσης. Το HomiDirect διατηρεί το δικαίωμα να αφαιρέσει οποιαδήποτε καταχώρηση που παραβιάζει τους όρους μας.",
    "terms.section5.title": "5. Αποποίηση Ευθύνης",
    "terms.section5.content": "Το HomiDirect δρα ως πλατφόρμα για τη σύνδεση ιδιοκτητών ακινήτων και ενοικιαστών. Δεν εγγυόμαστε την ακρίβεια των καταχωρήσεων ή τη συμπεριφορά των χρηστών. Όλες οι συμφωνίες ενοικίασης γίνονται απευθείας μεταξύ των μερών.",
    "terms.section6.title": "6. Περιορισμός Ευθύνης",
    "terms.section6.content": "Το HomiDirect δεν ευθύνεται για τυχόν ζημίες που προκύπτουν από τη χρήση της υπηρεσίας μας, συμπεριλαμβανομένων, ενδεικτικά, άμεσων, έμμεσων, τυχαίων ή επακόλουθων ζημιών.",
    "terms.section7.title": "7. Αλλαγές στους Όρους",
    "terms.section7.content": "Διατηρούμε το δικαίωμα να τροποποιήσουμε αυτούς τους όρους ανά πάσα στιγμή. Η συνεχής χρήση της υπηρεσίας μετά από αλλαγές συνιστά αποδοχή των νέων όρων.",

    // Contact Page
    "contact.title": "Επικοινωνήστε μαζί μας",
    "contact.subtitle": "Έχετε ερωτήσεις; Θα χαρούμε να ακούσουμε από εσάς. Στείλτε μας ένα μήνυμα και θα απαντήσουμε το συντομότερο δυνατόν.",
    "contact.backToHome": "Επιστροφή στην Αρχική",
    "contact.email": "Email",
    "contact.phone": "Τηλέφωνο",
    "contact.address": "Διεύθυνση",
    "contact.formTitle": "Στείλτε μας ένα μήνυμα",
    "contact.name": "Όνομα",
    "contact.namePlaceholder": "Το πλήρες όνομά σας",
    "contact.emailLabel": "Email",
    "contact.emailPlaceholder": "to.email.sas@example.com",
    "contact.subject": "Θέμα",
    "contact.subjectPlaceholder": "Σχετικά με τι είναι;",
    "contact.message": "Μήνυμα",
    "contact.messagePlaceholder": "Πείτε μας πώς μπορούμε να σας βοηθήσουμε...",
    "contact.sendMessage": "Αποστολή Μηνύματος",
    "contact.messageSent": "Το Μήνυμα Στάλθηκε!",
    "contact.messageSentDesc": "Λάβαμε το μήνυμά σας και θα επικοινωνήσουμε μαζί σας σύντομα.",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
